flags: {}
packages:
- 'servant-auth'
- 'servant-auth-server'
- 'servant-auth-client'
- 'servant-auth-docs'
extra-deps:
- jose-0.5.0.0
- servant-0.8
- servant-server-0.8
- servant-client-0.8
- servant-docs-0.8
resolver: lts-6.7
