resolver: nightly-2020-08-31
packages:
- servant-auth
- servant-auth-server
- servant-auth-client
- servant-auth-docs
- servant-auth-swagger
extra-deps: 
- servant-client-core-0.18
- servant-server-0.18
- servant-client-0.18
- servant-swagger-1.1.10
- servant-docs-0.11.6
- base64-bytestring-1.0.0.3
